# Generated by Django 4.1.2 on 2022-10-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Введите имя с заглавной буквы",
                        max_length=100,
                        verbose_name="Имя",
                    ),
                ),
                (
                    "patronymic",
                    models.CharField(
                        blank=True,
                        help_text="Введите отчество",
                        max_length=100,
                        null=True,
                        verbose_name="Отчество",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Введите фамилию",
                        max_length=100,
                        verbose_name="Фамилия",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        help_text="Введите цель выдачи справки",
                        max_length=100,
                        verbose_name="Цель выдачи справки",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        help_text="Введите количество экземпляров справки",
                        verbose_name="Количество экземпляров справки",
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        help_text="Введите комментарий к справке",
                        max_length=255,
                        null=True,
                        verbose_name="Комментарий к справке",
                    ),
                ),
                (
                    "date_of_changes",
                    models.DateField(
                        blank=True,
                        help_text="Введите дату изменения",
                        null=True,
                        verbose_name="Дaтa изменения",
                    ),
                ),
            ],
        ),
    ]
