# Generated by Django 4.1.2 on 2022-10-23 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mystrictapplicationformapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Author", new_name="Reference",),
    ]
