# Generated by Django 4.1.2 on 2022-10-25 14:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mystrictapplicationformapp", "0002_rename_author_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="date_of_changes",
            field=models.DateField(
                blank=True,
                default=datetime.date(2022, 10, 25),
                help_text="Введите дату изменения",
                null=True,
                verbose_name="Дaтa изменения",
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Введите количество экземпляров справки",
                validators=[django.core.validators.MaxValueValidator(10)],
                verbose_name="Количество экземпляров справки",
            ),
        ),
    ]
